### ISSUE TITLE
NullReferenceException on generating context menu

### ISSUE THREAD

**Issue by vincentsels** [conwid/DependencyInjectionToolset#11]
I get this error practically every time I press ctrl+. on a constructor parameter. Even though the error then mentions that the plugin has been disabled, I can just continue to use the 'introduce read-only property' action (even without having to click 'enable' or 'enable and ignore future errors'). So it doesn't seem to leave the plugin in a corrupt state... But it's very annoying, of course.

It appears very randomly. Sometimes it appears every time, sometimes it no longer appears when I click 'enable and ignore future errors',...

'IntroduceFieldRefactoringCodeRefactoringProvider' encountered an error and has been disabled.

Stack trace:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async IntroduceFieldRefactoring.IntroduceFieldRefactoringCodeRefactoringProvider.CreateFieldAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

VS version: VS Enterprise 2017, 15.8.3

**Comment by conwid** [comment]
Thanks for bringing this issue to my attention.
To diagnose the problem further, I'd like to ask if you have experienced this with older version of the extension as well, or just the newest one?
Also, if possible, could you provide a little code snippet to reproduce the issue?

Thanks!

**Comment by conwid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dependency injection toolset bug](https://trello.com/c/7IAiuZjC/4-dependency-injection-toolset-bug)

**Comment by vincentsels** [comment]
Thanks for your prompt reply! I've been encountering this issue since the beginning, I think about half a year ago, so yes, I've had it with any version of the plugin (and older versions of VS) during that period...

Did some more testing, and actually, for me it crashes reliably every time I use ctrl+. (or also when I expand the context refactoring menu using the lightbulb icon), until I choose to enable and ignore future errors. It doesn't seem to depend on anything specific. But as mentioned above, even though it throws the error, and VS seems to mention that it disabled the plugin, it just continues to work regardless, even without explicitly enabling it again.

![2018-09-12_105311](https://user-images.githubusercontent.com/1068863/45415033-fce70a80-b67c-11e8-9b53-c3efb883e4db.png)

**Comment by vincentsels** [comment]
Wait a minute... is this even your plug-in, or is this something from Resharper which I only discovered after having installed your plug-in? :D

**Comment by conwid** [comment]
If you have some time and could do some further testing without resharper, that would be helpful. I myself don't use it and have no license to test.

**Comment by vincentsels** [comment]
Oh boy, so it turns out that this is actually a Resharper functionality, which I didn't know existed, and which I mistakenly thought was your plugin :'). That of course explains why it 'continued working even though your plugin crashed and was disabled' :'). Haha, so silly of me.

I did a quick test and even with Resharper disabled, I still reliably get the same error though. Not sure what could be causing it here... Maybe a complete re-install of VS and the plugin would fix it; but since I kind of no longer need your plugin now that I found out I can also do it with Resharper, I'm not immediately planning on going through that hassle ;).

If you can't find a certain explanation just based on the stack trace, I'll close this issue as I'm guessing there's no way you could reproduce this on your end...

Sorry for your time, I feel really silly! :)

**Comment by conwid** [comment]
Thanks for looking into this a little bit more. I'm sorry to hear you're moving on to resharper, but of course I understand it :)
Anyway, I think I will look into this a little more closely, maybe I'll have some luck with just the stacktrace...

**Comment by conwid** [comment]
Unfortunately I wasn't able to reproduce the issue, so for now, I close it.
