### ISSUE TITLE
Constructor injection option doesn't show up if type isn't resolved

### ISSUE THREAD

**Issue by GrantByrne** [conwid/DependencyInjectionToolset#2]
I've noticed a bug when I first tried using this add-on. At first I thought the add-on didn't work, but I was able to figure out a workaround.

**Steps to Reproduce**
- Create a new class with a constructor
- Define a property in the constructor to be injected in that isn't referenced in the using statements
- Use ctrl+. to add the using reference
- *Result* - The option for creating the field for the property never shows up.

The workaround for this is to delete the injected property and then retype it.

**Comment by conwid** [comment]
Thanks for taking the time to figure out how to reproduce the issue and describing it in detail.
I will look into it asap and hopefully find a fix :)

**Comment by GrantByrne** [comment]
I created a fix for this. You can check out the pull request here: https://github.com/conwid/DependencyInjectionToolset/pull/3

**Comment by conwid** [comment]
Thank you for the fix. I've merged with the master and deployed a new version to the marketplace.
