### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by stiansandberg** [conwid/DependencyInjectionToolset#4]
Thanks for a great extension!
Will there be a version for VS2017 soon?

**Comment by conwid** [comment]
Glad you like it!
Definitely. I think the extension itself should work for VS2017 with little to no modification, I just have to repackage it. Give me some time and I will look into it.

**Comment by ichpuchtli** [comment]
👍 yes please :)
Perfect extension (only thing I wanted from resharper)

**Comment by conwid** [comment]
Merged PR #5 , extension published, available in the marketplace.
